version: "3.8"
services:
  app:
    container_name: server_back_nest_node_lts
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:3000 
    networks:
      - pras_net    
    hostname: backend_nest
    volumes:
      - ./src:/app/src
networks:
  pras_net:
    name: apps-net
    external: true 
    
volumes:
  src: {}