version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node-lts-nest
    restart: always
    ports:
      - 5000:3000
    volumes:
      - ./src:/app/src
volumes:
  src: {}